version: '3.9'

services:
  api:
    build:
      context: ./MiniEcommerceCase
      dockerfile: Dockerfile
    container_name: mini-ecommerce-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=MyUltraSecureJwtKey_1234567890123456
      - Jwt__Issuer=MiniEcommerce
      - Jwt__Audience=MiniEcommerceUsers
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
